import { AiFillStar } from "react-icons/ai";

const Fashion = [
  {
    id: "30",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing1.jpg",
    title: "Cotton Printed Pyjama",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "white",
    category: "kids",
    desc: "printed pyjama",
  },
  {
    id: "31",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing2.jpg",
    title: "100% Cotton Nightwear ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "red",
    category: "kids",
    desc: "Watermelon Print",
  },

  {
    id: "32",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing3.jpg",
    title: "Cotton Printed T-shirt & Short ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "ARIEL",
    color: "sky",
    category: "kids",
    desc: "printed T-shirt",
  },
  {
    id: "33",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing4.jpg",
    title: "Cotton Dino Printed T-shirt With Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Googogaaga",
    color: "white",
    category: "kids",
    desc: "printed shorts",
  },
  {
    id: "34",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing5.jpg",
    title: "Formal Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "white",
    category: "kids",
    desc: "formal set",
  },
  {
    id: "35",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing6.jpg",
    title: "Graphic Print Shirt And Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Hopscotch",
    color: "navy",
    category: "kids",
    desc: "Shirt And Pant Set",
  },

  {
    id: "36",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing7.jpg",
    title: "T-Shirt with Denim Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Googo Gaaga",
    color: "red",
    category: "kids",
    desc: "Shorts Set",
  },

  {
    id: "37",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing8.jpg",
    title: "Print T-Shirt With Jacket",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "green",
    category: "kids",
    desc: "printed set",
  },

  {
    id: "38",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing1.jpg",
    title: "Cotton Rich Solid Polo T-Shirt Regular Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Symbol",
    color: "red",
    category: "men",
    desc: "Men's Cotton T-Shirt Regular",
  },

  {
    id: "39",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing2.jpg",
    title: "Casual Shirt for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Lymio",
    color: "gray",
    category: "men",
    desc: "Men Stylish Shirt (Rib-Shirt)",
  },
  {
    id: "40",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing3.jpg",
    title: "Men's Regular Fit Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "DHRUVI TRENDZ ",
    color: "blue",
    category: "men",
    desc: "printed leaf",
  },
  {
    id: "41",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing4.jpg",
    title: "Allday Fresh Buttondown Oxford Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Symbol Premium",
    color: "blue",
    category: "men",
    desc: "regular fit solid blue",
  },
  {
    id: "42",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing5.jpg",
    title: "Slim Fit Cotton Casual Printed Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Majestic Man",
    color: "mix",
    category: "men",
    desc: "printed Shirt",
  },
  {
    id: "43",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing6.jpg",
    title: "Track Pant for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Lymio",
    color: "gray",
    category: "men",
    desc: "Plain Track Pant",
  },

  {
    id: "45",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing7.jpg",
    title: "Men Cargo Pants",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Lymio",
    color: "gray",
    category: "sneakers",
    desc: "Men Cargo Pants Cotton",
  },
  {
    id: "46",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing8.jpg",
    title: "Men Pajama Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "DHRUVI TRENDZ",
    color: "white",
    category: "men",
    desc: "printed Pajama Set",
  },
  {
    id: "47",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing1.jpg",
    title: "Co Ord Set for Women Ethnic Wear ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Leriya Fashion",
    color: "mix",
    category: "women",
    desc: "printed set",
  },
  {
    id: "48",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing2.jpg",
    title: "Viscose Embroidered Kurti Pant and Dupatta Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "KLOSIA",
    color: "merun",
    category: "women",
    desc: "Embroidered set",
  },
  {
    id: "49",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing3.jpg",
    title: "Cotton Printed Straight Kurta and Pant Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "rytras",
    color: "white",
    category: "women",
    desc: "printed set",
  },
  {
    id: "50",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing4.jpg",
    title: "Floral Printed Cotton Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "rytras",
    color: "blue",
    category: "women",
    desc: "printed set",
  },
  {
    id: "51",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing5.jpg",
    title: "one Piece Dress for Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Amazon Brand",
    color: "red",
    category: "women",
    desc: "printed set",
  },
  {
    id: "52",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing6.jpg",
    title: "omen's Rayon Standard Neck Fancy Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "GRECIILOOKS",
    color: "white",
    category: "women",
    desc: "printed top",
  },
  {
    id: "53",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing7.jpg",
    title: "Women Coord Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "GRECIILOOKS",
    color: "mix",
    category: "women",
    desc: "Coord Set",
  },

  {
    id: "54",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\women\wclothing8.jpg",
    title: "One Piece Dress for Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Leriya Fashion ",
    color: "pink",
    category: "women",
    desc: "Beach Dress for Women",
  },
  // {
  //   id: "55",
  //   img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing1.1.jpg",
  //   title: "Chunky High Heel",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   desc: "printed set",
  // },
  // {
  //   id: "56",
  //   img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
  //   title: "Amore Fashion Stilettos",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "150",
  //   company: "Adidas",
  //   color: "white",
  //   category: "heels",
  //   desc: "printed set",
  // },
  // {
  //   id: "57",
  //   img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
  //   title: "Bridal Sandals Glitter",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "heels",
  //   desc: "printed set",
  // },
  // {
  //   id: "58",
  //   img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
  //   title: "Wedding Prom Bridal",
  //   star: <AiFillStar className="rating-star" />,
  //   reviews: "(123 reviews)",
  //   prevPrice: "$140,00",
  //   newPrice: "50",
  //   company: "Adidas",
  //   color: "black",
  //   category: "flats",
  //   desc: "printed set",
  // },
];

export default Fashion;
