import { AiFillStar } from "react-icons/ai";

const Fashion = [
  {
    id: "30",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing1.jpg",
    title: "Cotton Printed Pyjama",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "white",
    category: "kids",
    desc: "printed pyjama",
  },
  {
    id: "31",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing2.jpg",
    title: "100% Cotton Nightwear ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "red",
    category: "kids",
    desc: "Watermelon Print",
  },

  {
    id: "32",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing3.jpg",
    title: "Cotton Printed T-shirt & Short ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "ARIEL",
    color: "sky",
    category: "kids",
    desc: "printed T-shirt",
  },
  {
    id: "33",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing4.jpg",
    title: "Cotton Dino Printed T-shirt With Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Googogaaga",
    color: "white",
    category: "kids",
    desc: "printed shorts",
  },
  {
    id: "34",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing5.jpg",
    title: "Formal Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "white",
    category: "kids",
    desc: "formal set",
  },
  {
    id: "35",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing6.jpg",
    title: "Graphic Print Shirt And Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Hopscotch",
    color: "navy",
    category: "kids",
    desc: "Shirt And Pant Set",
  },

  {
    id: "36",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing7.jpg",
    title: "T-Shirt with Denim Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Googo Gaaga",
    color: "red",
    category: "kids",
    desc: "Shorts Set",
  },

  {
    id: "37",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing8.jpg",
    title: "Print T-Shirt With Jacket",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "green",
    category: "kids",
    desc: "printed set",
  },

  {
    id: "38",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing1.jpg",
    title: "Cotton Rich Solid Polo T-Shirt Regular Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Symbol",
    color: "red",
    category: "men",
    desc: "Men's Cotton T-Shirt Regular",
  },

  {
    id: "39",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing2.jpg",
    title: "Casual Shirt for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Lymio",
    color: "gray",
    category: "men",
    desc: "Men Stylish Shirt (Rib-Shirt)",
  },
  {
    id: "40",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing3.jpg",
    title: "Men's Regular Fit Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "DHRUVI TRENDZ ",
    color: "blue",
    category: "men",
    desc: "printed leaf",
  },
  {
    id: "41",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing4.jpg",
    title: "Allday Fresh Buttondown Oxford Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Symbol Premium",
    color: "blue",
    category: "men",
    desc: "regular fit solid blue",
  },
  {
    id: "42",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing5.jpg",
    title: "Slim Fit Cotton Casual Printed Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Majestic Man",
    color: "mix",
    category: "men",
    desc: "printed Shirt",
  },
  {
    id: "43",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing6.jpg",
    title: "Track Pant for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Lymio",
    color: "gray",
    category: "men",
    desc: "Plain Track Pant",
  },

  {
    id: "45",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing7.jpg",
    title: "Men Cargo Pants",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Lymio",
    color: "gray",
    category: "sneakers",
    desc: "Men Cargo Pants Cotton",
  },
  {
    id: "46",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\men\menclothing8.jpg",
    title: "Men Pajama Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "DHRUVI TRENDZ",
    color: "white",
    category: "men",
    desc: "printed Pajama Set",
  },
  {
    id: "47",
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
    desc: "printed set",
  },
  {
    id: "48",
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
    desc: "printed set",
  },
  {
    id: "49",
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
    desc: "printed set",
  },
  {
    id: "50",
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "51",
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "52",
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "53",
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    desc: "printed set",
  },

  {
    id: "54",
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "55",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing1.1.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "56",
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "57",
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    desc: "printed set",
  },
  {
    id: "58",
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    desc: "printed set",
  },
];

export default Fashion;
