import { AiFillStar } from "react-icons/ai";

const Mobiles = [
  {
    id: "30",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing1.jpg",
    title: "Cotton Printed Pyjama",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "white",
    category: "kids",
    desc: "printed pyjama",
  },
  {
    id: "31",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing2.jpg",
    title: "100% Cotton Nightwear ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Mom Store",
    color: "red",
    category: "kids",
    desc: "Watermelon Print",
  },

  {
    id: "32",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing3.jpg",
    title: "Cotton Printed T-shirt & Short ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "ARIEL",
    color: "sky",
    category: "kids",
    desc: "printed T-shirt",
  },
  {
    id: "33",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing4.jpg",
    title: "Cotton Dino Printed T-shirt With Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Googogaaga",
    color: "white",
    category: "kids",
    desc: "printed shorts",
  },
  {
    id: "34",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing5.jpg",
    title: "Formal Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "white",
    category: "kids",
    desc: "formal set",
  },
  {
    id: "35",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing6.jpg",
    title: "Graphic Print Shirt And Pant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Hopscotch",
    color: "navy",
    category: "kids",
    desc: "Shirt And Pant Set",
  },

  {
    id: "36",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing7.jpg",
    title: "T-Shirt with Denim Shorts",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Googo Gaaga",
    color: "red",
    category: "kids",
    desc: "Shorts Set",
  },

  {
    id: "37",
    img: "C:\Users\HP\Desktop\Projects\react\MultiVendor_E-commerce\Frontend\src\assets\Fashion\kids\kclothing8.jpg",
    title: "Print T-Shirt With Jacket",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Hopscotch",
    color: "green",
    category: "kids",
    desc: "printed set",
  },
];

export default Mobiles;